version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

configuration: Release

test: off

install:
  - dotnet restore

after_build:
  - dotnet pack

build:
  parallel: true
  project: OmdbRest.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
artifacts:
  - path: src\bin\$(configuration)
    name: bin
  - path: '**\*.nupkg'
    name: nuget