version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

install:
  - dotnet restore

cache:
  - packages -> paket.lock

build:
  parallel: true
  project: OmdbRest.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
artifacts:
  - path: src\bin\$(configuration)\OmdbRest.dll
  - path: src\bin\$(configuration)\OmdbRest.pdb

deploy:
  - provider: GitHub
    release: OmdbRest-v$(appveyor_build_version)
    auth_token:
      secure: AKvncEaWXvKGoLiiYaxf3NvS+ZIlExjXhc9hugLtkig2sot+nSYrxN15M8IjkN3A
    artifact: /.*\.(dll|pdb|nupkg)/
    draft: false
    prerelease: false
    on:
      branch: master

  - provider: NuGet
    api_key:
      secure: 3lx2hPglCgr4j9T+TbHIsHTNwwwxq7WsDk7poMu6KjwLS3pUHNW3HWC6xtikKMI/
    skip_symbols: false
    artifact: /.*\.nupkg/
